doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
#        server_version: '5.6'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
#doctrine:
#    orm:
#        auto_generate_proxy_classes: false
#        metadata_cache_driver:
#            type: service
#            id: doctrine.system_cache_provider
#        query_cache_driver:
#            type: service
#            id: doctrine.system_cache_provider
#        result_cache_driver:
#            type: service
#            id: doctrine.result_cache_provider
#
#services:
#    doctrine.result_cache_provider:
#        class: Symfony\Component\Cache\DoctrineProvider
#        public: false
#        arguments:
#            - '@doctrine.result_cache_pool'
#    doctrine.system_cache_provider:
#        class: Symfony\Component\Cache\DoctrineProvider
#        public: false
#        arguments:
#            - '@doctrine.system_cache_pool'
#
#framework:
#    cache:
#        pools:
#            doctrine.result_cache_pool:
#                adapter: cache.app
#            doctrine.system_cache_pool:
#                adapter: cache.system
