doctrine_migrations:
#    dir_name: '%kernel.project_dir%/src/Migrations'
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
# Old Format
#    migrations_paths:
#        # namespace is arbitrary but should be different from App\Migrations
#        # as migrations classes should NOT be autoloaded
##        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
#        'App\Migrations': '%kernel.project_dir%/src/Migrations'
