endroid_qr_code:
    writer: Endroid\QrCode\Writer\PngWriter
    size: 250
    margin: 10
    errorCorrectionLevel: 'low'
    validateResult: false
    logoResizeToWidth: 60
    logoResizeToHeight: 60
