fm_elfinder:
    instances:
        default:
#            locale: '%locale%'
            editor: ckeditor
            fullscreen: true
            theme: smoothness
            relative_path: false

            connector:
                debug: false
                roots:
                    uploads:
                        show_hidden: false
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M
                        url: '%env(APP_URL_IMAGES)%'
        form:
#            locale: '%locale%' # defaults to current request locale
            editor: ckeditor # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            connector:
                debug: false # defaults to false
                roots: # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M
                        url: '%env(APP_URL_IMAGES)%'
