#fm_elfinder:
#    resource: "@FMElfinderBundle/Resources/config/routing.yaml"

ef_connect:
    path:  /assets/efconnect/{instance}/{homeFolder}
    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::load, instance: default, homeFolder: '' }
#    requirements:
#        _locale: '%app_locales%'

ef_main_js:
    path:  /assets/elfinder.main.js
    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::mainJS }
#    requirements:
#        _locale: '%app_locales%'

elfinder:
    #    path: /elfinder/{instance}/{homeFolder}
    #    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::show, instance: default, homeFolder: '' }
    #    elfinder:
    path: /assets/elfinder/{instance}/{homeFolder}
    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::show, instance: default, homeFolder: '' }
#    requirements:
#        _locale: '%app_locales%'


#fm_elfinder:
#    resource: "@FMElfinderBundle/Resources/config/routing.yaml"
