App\Entity\Celebracion:
  attributes:
    normalization_context:
      groups: [celebracion_read]
  collectionOperations:
    getcelebracion:
      path: getcelebracion
      controller: App\Action\Celebracion\GetCelebraciones
      method: GET
      deserialize: false
      openapi_context:
        summary: Obtiene el listado de celebraciones disponibles
  itemOperations:
    get:
      method: GET
