controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\ZinicioController::index

homepage:
    path: /
    controller: App\Controller\ZinicioController::index





#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
kernel:
    resource: ../src/Kernel.php
    type: annotation
