#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\InicioController::index


#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
