controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#index:
#    path: /
#    controller: App\Controller\ZinicioController::index

