# config/packages/symfony_ckeditor5.yaml
symfony_ckeditor5:
  editors:
    custom1:
      toolbar:
        items:
          - "sourceEditing"
          - "|"
          - "undo"
          - "redo"
          - "|"
          - "heading"
          - "|"
          - "bold"
          - "italic"
          - "fontColor"
          - "|"
          - "fontFamily"
          - "fontSize"
          - "fontBackgroundColor"
          - "|"
          - "bulletedList"
          - "numberedList"
          - "todoList"
          - "|"
          - "link"
          - "|"
          - "code"
          - "|"
          - label: "Media Options"
            icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0H576c35.3 0 64 28.7 64 64V288c0 35.3-28.7 64-64 64H256c-35.3 0-64-28.7-64-64V64c0-35.3 28.7-64 64-64zM476 106.7C471.5 100 464 96 456 96s-15.5 4-20 10.7l-56 84L362.7 169c-4.6-5.7-11.5-9-18.7-9s-14.2 3.3-18.7 9l-64 80c-5.8 7.2-6.9 17.1-2.9 25.4s12.4 13.6 21.6 13.6h80 48H552c8.9 0 17-4.9 21.2-12.7s3.7-17.3-1.2-24.6l-96-144zM336 96a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zM64 128h96V384v32c0 17.7 14.3 32 32 32H320c17.7 0 32-14.3 32-32V384H512v64c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V192c0-35.3 28.7-64 64-64zm8 64c-8.8 0-16 7.2-16 16v16c0 8.8 7.2 16 16 16H88c8.8 0 16-7.2 16-16V208c0-8.8-7.2-16-16-16H72zm0 104c-8.8 0-16 7.2-16 16v16c0 8.8 7.2 16 16 16H88c8.8 0 16-7.2 16-16V312c0-8.8-7.2-16-16-16H72zm0 104c-8.8 0-16 7.2-16 16v16c0 8.8 7.2 16 16 16H88c8.8 0 16-7.2 16-16V416c0-8.8-7.2-16-16-16H72zm336 16v16c0 8.8 7.2 16 16 16h16c8.8 0 16-7.2 16-16V416c0-8.8-7.2-16-16-16H424c-8.8 0-16 7.2-16 16z"/></svg>'
            items:
              - "mediaEmbed"
              - "|"
              - "uploadImage"
          - "|"
          - label: "Basic Styles"
            icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M504.3 11.1C493.3-1.6 474.5-3.7 461 6.2L252.3 160H397.3L502.6 54.6c11.8-11.8 12.6-30.8 1.6-43.5zM32 192c-17.7 0-32 14.3-32 32s14.3 32 32 32c0 82.5 43.4 147.7 123.9 176.2c-11.1 13.9-19.4 30.3-23.9 48.1C127.6 497.4 142.3 512 160 512H352c17.7 0 32.4-14.6 28.1-31.7c-4.5-17.8-12.8-34.1-23.9-48.1C436.6 403.7 480 338.5 480 256c17.7 0 32-14.3 32-32s-14.3-32-32-32H32z"/></svg>'
            items:
              - "strikethrough"
              - "subscript"
              - "superscript"
              - "alignment"
              - "blockQuote"
              - "codeBlock"
              - "insertTable"
              - "outdent"
              - "indent"
              - "textPartLanguage"
        shouldNotGroupWhenFull: false

      language: "es"

      table:
        contentToolbar:
          - "tableColumn"
          - "tableRow"
          - "mergeTableCells"

      image:
        resizeOptions:
          - name: "resizeImage:original"
            value: null
            label: "Original"
          - name: "resizeImage:100"
            value: "100"
            label: "100%"
          - name: "resizeImage:60"
            value: "60"
            label: "60%"
          - name: "resizeImage:50"
            value: "50"
            label: "50%"
          - name: "resizeImage:40"
            value: "40"
            label: "40%"
          - name: "resizeImage:30"
            value: "30"
            label: "30%"
          - name: "resizeImage:20"
            value: "20"
            label: "20%"
        toolbar:
          - "linkImage"
          - "|"
          - "imageStyle:inline"
          - "imageStyle:wrapText" # Dropdown for `alignLeft` and `alignRight`.
          - "imageStyle:breakText" # Dropdown for `alignBlockLeft`, `block`, and `alignBlockRight`.
          - "|"
          - "resizeImage"
          - "|"
          - "toggleImageCaption"
          - "imageTextAlternative"
        insert:
          type: "auto"
      cloudServices:
        - uploadUrl: "https://example.yourdomain/fileupload"
        - tokenUrl: "https://example.yourdomain/token"
      list:
        properties:
          styles: true
          startIndex: true
          reversed: true
      mediaEmbed:
        toolbar:
          - "mediaEmbed"
        extraProviders:
          - name: "ckeditor"
            url: "ckeditor.com"
        removeProviders:
          ["instagram", "twitter", "googleMaps", "flickr", "facebook"]
        providers:
          - url: /^example\.com\/media\/(\w+)/
            html: match => "..."
            name: "example"

      htmlSupport:
        allow:
          - name: "/.*/"
            attributes: true
            classes: true
            styles: true
