App\Entity\Celebracion:
  attributes:
    id:
      groups: [celebracion_read]
    fechaCelebracionAt:
      groups: [celebracion_read]
    nombre:
      groups: [celebracion_read]
    capacidad:
      groups: [celebracion_read]
    descripcion:
      groups: [celebracion_read]
    imageQr:
      groups: [celebracion_read]
    groupCelebrations:
      groups: [celebracion_read]
    disponibleAt:
      groups: [celebracion_read]
    disponibleHastaAt:
      groups: [celebracion_read]